// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/carloscfgos1980/graphql-habit-tracker/internal/models"
)

type AuthPayLoad struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type Habit struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	Description   *string      `json:"description,omitempty"`
	CurrentStreak int32        `json:"currentStreak"`
	LongerStreak  int32        `json:"longerStreak"`
	HabitLogs     []*HabitLog  `json:"habitLogs"`
	IsCompleted   bool         `json:"isCompleted"`
	User          *models.User `json:"user"`
	CreatedAt     string       `json:"createdAt"`
	UpdatedAt     string       `json:"updatedAt"`
}

type HabitLog struct {
	ID            string `json:"id"`
	CompletedDate string `json:"completedDate"`
	Habit         *Habit `json:"habit"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}
