package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"github.com/carloscfgos1980/graphql-habit-tracker/internal/graph/generated"
)

// Habit returns generated.HabitResolver implementation.
func (r *Resolver) Habit() generated.HabitResolver { return &habitResolver{r} }

// HabitLog returns generated.HabitLogResolver implementation.
func (r *Resolver) HabitLog() generated.HabitLogResolver { return &habitLogResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	habitResolver    struct{ *Resolver }
	habitLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *habitLogResolver) UpdatedAt(ctx context.Context, obj *models.HabitLog) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}
*/
