package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/carloscfgos1980/graphql-habit-tracker/internal/graph/generated"
	"github.com/carloscfgos1980/graphql-habit-tracker/internal/models"
)

// CurrentStreak is the resolver for the currentStreak field.
func (r *habitResolver) CurrentStreak(ctx context.Context, obj *models.Habit) (int32, error) {
	panic(fmt.Errorf("not implemented: CurrentStreak - currentStreak"))
}

// LongestStreak is the resolver for the longestStreak field.
func (r *habitResolver) LongestStreak(ctx context.Context, obj *models.Habit) (int32, error) {
	panic(fmt.Errorf("not implemented: LongestStreak - longestStreak"))
}

// TotalCompletions is the resolver for the totalCompletions field.
func (r *habitResolver) TotalCompletions(ctx context.Context, obj *models.Habit) (int32, error) {
	panic(fmt.Errorf("not implemented: TotalCompletions - totalCompletions"))
}

// Logs is the resolver for the logs field.
func (r *habitResolver) Logs(ctx context.Context, obj *models.Habit) ([]*models.HabitLog, error) {
	panic(fmt.Errorf("not implemented: Logs - logs"))
}

// Name is the resolver for the name field.
func (r *userResolver) Name(ctx context.Context, obj *models.User) (string, error) {
	return obj.Username, nil
}

// Habits is the resolver for the habits field.
func (r *userResolver) Habits(ctx context.Context, obj *models.User) ([]*models.Habit, error) {
	return []*models.Habit{}, nil
}

// Habit returns generated.HabitResolver implementation.
func (r *Resolver) Habit() generated.HabitResolver { return &habitResolver{r} }

// HabitLog returns generated.HabitLogResolver implementation.
func (r *Resolver) HabitLog() generated.HabitLogResolver { return &habitLogResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	habitResolver    struct{ *Resolver }
	habitLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *habitLogResolver) UpdatedAt(ctx context.Context, obj *models.HabitLog) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}
*/
